Removed errors caused by repeated connection to signals.
unknown-horizons/godot-port pull request #105
Opened 2023-02-25 11:44 UTC by hepfnepf

1. Selecting the road builder would cause an error after the first time. `connect: Signal 'tiles_changed' is already connected to given method 'update_tiles' in that object.`
This was because it tried to connect the stiles_changed signal ervery time. Thus i moved it to ready.
2. The signal wiring in the switch widgets was completly broken. It appears, the original author wanted to notify all SwitchTabWidgets every the tab changes. But insted, every first time a widget got selected, it tried to connect the same signal 5 time to itself, insted of to the other nodes. Therefore making the system not work and also throwing already connected errors. This is now fixed. I think it would make more sense though, to move the signal wiring and tabcontainer setting to the parent node. I kept the code in here, because it seems the original auther explicitly wanted to have it here.

2023-03-12 16:33 UTC, artism90 commented on Assets/Player/InteractionContexts/TileContext.gd
```suggestion

```

2023-03-12 16:33 UTC, artism90 commented on Assets/UI/Scenes/TabWidgets/Switches/SwitchTabWidget.gd
```suggestion

```

2023-03-12 16:33 UTC, artism90 commented on Assets/UI/Scenes/TabWidgets/Switches/SwitchTabWidget.gd
> +				switch.tab_container=tab_container
```suggestion
				switch.tab_container = tab_container
```

2023-03-12 16:36 UTC, artism90 requested changes
Please fix the remarked code style issues (blank lines, spacing) and squash the commit before merging.

2023-03-17 09:26 UTC, LinuxDonald commented
@hepfnepf could you please fix your other pr too :-)

2023-03-17 15:54 UTC, merged