Added functionality to the speed buttons.
unknown-horizons/godot-port pull request #106
Opened 2023-02-25 15:56 UTC by hepfnepf

The speed up and down buttons now work and the current speed gets displayed on the label.

2023-03-12 17:03 UTC, artism90 commented on Assets/UI/Scenes/TabWidgets/Buttons/MainButtons/Buttons/SpeedChangeButton.gd
> +export (float) var speed_change = 0.0
```suggestion
export(float) var game_speed_change = 0.0
```

2023-03-12 17:04 UTC, artism90 commented on Assets/UI/Scenes/TabWidgets/Buttons/MainButtons/Buttons/SpeedChangeButton.gd
> +	Global.Game.set_game_speed(Engine.time_scale+speed_change)
```suggestion
	Global.Game.set_game_speed(Engine.time_scale + game_speed_change)
```

2023-03-12 17:05 UTC, artism90 commented on Assets/UI/Scripts/SpeedLabel.gd
> +class_name SpeedLabel
```suggestion
class_name GameSpeedLabel
```

2023-03-12 17:05 UTC, artism90 commented on Assets/UI/Scripts/SpeedLabel.gd
> +	call_deferred("connect_game")#waiting for Global.Game to be set
```suggestion
	call_deferred("connect_game") # waiting for Global.Game to be set
```

2023-03-12 17:06 UTC, artism90 commented on Assets/UI/Scripts/SpeedLabel.gd
> +	Global.Game.connect("speed_changed",self,"_on_speed_changed")
```suggestion
	Global.Game.connect("game_speed_changed", self, "_on_game_speed_changed")
```

2023-03-12 17:06 UTC, artism90 commented on Assets/UI/Scripts/SpeedLabel.gd
> +func _on_speed_changed(new_speed:float) -> void:
```suggestion
func _on_speed_changed(new_game_speed: float) -> void:
```

2023-03-12 17:06 UTC, artism90 commented on Assets/UI/Scripts/SpeedLabel.gd
> +	text = "%1.1fx" % new_speed
```suggestion
	text = "%1.1fx" % new_game_speed
```

2023-03-12 17:07 UTC, artism90 commented on Assets/World/Game.gd
> +const MAX_SPEED:float = 2.0
```suggestion
signal game_speed_changed(new_game_speed)

const MAX_GAME_SPEED: float = 2.0
```

2023-03-12 17:09 UTC, artism90 commented on Assets/World/Game.gd
> +	emit_signal("speed_changed",Engine.time_scale)
```suggestion
func set_game_speed(game_speed: float) -> void:
	Engine.time_scale = clamp(game_speed, 0.0, MAX_GAME_SPEED)
	print_debug("Game speed changed to ", Engine.time_scale)
	emit_signal("game_speed_changed", Engine.time_scale)
```

2023-03-12 17:11 UTC, artism90 requested changes
Please fix the marked code style issues.
I suggest to rename all instances of `Speed`/`speed`/`SPEED` into `GameSpeed`/`game_speed`/`GAME_SPEED` to avoid ambiguity. I've marked all occurrences that I could locate. Also the script names and the nodes from the TabWidget should be updated to clearly reflect their use.

2023-03-16 07:23 UTC, LinuxDonald commented
@hepfnepf will you do the needed changes please?

2023-03-17 15:58 UTC, artism90 approved these changes

2023-03-17 15:58 UTC, pingwindev approved these changes

2023-03-17 15:58 UTC, merged