Start working on the New Game screen
unknown-horizons/godot-port pull request #35
Opened 2019-01-30 22:04 UTC by Jummit

Working on #16.

2019-01-30 23:00 UTC, YeldhamDev commented
Just a tip: Start the pull's title with "WIP:" or "[WIP]" while it's still being worked on, so we can quickly see when it's ready.

2019-01-31 15:22 UTC, Jummit commented
> Just a tip: Start the pull's title with "WIP:" or "[WIP]" while it's still being worked on, so we can quickly see when it's ready.

Forgot that.

2019-01-31 21:25 UTC, YeldhamDev commented
You'll also have to squish this and your[ other pull](34)'s commits.

2019-01-31 21:55 UTC, Jummit commented
> You'll also have to squish this and your[ other pull](34)'s commits.

How do I do that? Is it [this](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)?

2019-01-31 21:57 UTC, YeldhamDev commented
Yep, turn those multiple commits into one.

2019-01-31 22:18 UTC, Jummit commented
Whats the reason to do so?

2019-01-31 22:30 UTC, YeldhamDev commented
A cleaner git history. Besides making much more sense to group together commits that are about a specific change, instead of being scattered around.
Looking at the commits, the main change here is turning the main menu buttons into their own scenes, and as far we care about, this is the only commit message we want.

2019-02-06 22:09 UTC, Jummit commented
Superseded by this [pull request](https://github.com/unknown-horizons/godot-port/pull/37).

2019-03-14 12:54 UTC, YeldhamDev commented
Apologies for not checking this pull sooner, should've tried to merge this first before upgrading the project to 3.1. Could you rebase this one more time?

2019-03-21 19:03 UTC, Jummit commented
> Apologies for not checking this pull sooner, should've tried to merge this first before upgrading the project to 3.1. Could you rebase this one more time?
Done.

2019-03-21 20:47 UTC, YeldhamDev commented
There's still a small conflict in the `icon.png.import` file.

2019-03-24 15:16 UTC, olivier-grech commented
I have a small suggestion. The checkbox for the game type (*Scenario*, *Random map*, *Free play*) can be unchecked by clicking on it.

I think it should behave like a set of radio buttons: one of the case is checked at first (let's say *Scenario*), and when you click on somethign that is checked it does nothing (therefore there is alway one case checked).

Here is an example of how you could do that for the `GameTypeButton.gd` script:

```
extends HBoxContainer

export var type = ""
export var checked = false

func _ready():
	$Label.text = type
	if checked:
		get_node("CheckBox").pressed = true


func _on_pressed():
	for type_button in get_parent().get_children():
		if type_button != self:
			type_button.get_node("CheckBox").pressed = false
	if !get_node("CheckBox").pressed:
		get_node("CheckBox").pressed = true
```

2019-03-24 15:23 UTC, olivier-grech commented
Another small suggestion, I think you should indicate the number of IA players selected, it is not very clear right now. Something like this:

![exampe](https://user-images.githubusercontent.com/12234562/54881504-0aadf180-4e51-11e9-8e8a-8750350fe262.png)

Though I am not sure if the leftmost option should be `1` or `0`.

2019-03-24 17:46 UTC, aaronfranke commented
Not only will you need to rebase, but you will also need to remove some files - I added `.DS_Store` to the `.gitignore` file.

2019-03-24 17:50 UTC, LinuxDonald commented
It should be 0 if anyone want to play without ai.

2019-04-12 21:08 UTC, aaronfranke requested changes
You need to rebase your commit using [a Git client](https://www.gitkraken.com/). Please see [PR workflow](https://godot.readthedocs.io/en/latest/community/contributing/pr_workflow.html).

2019-04-12 21:08 UTC, aaronfranke commented on Assets/UI/Scenes/MainMenuScene.tscn
> +[ext_resource path="res://Assets/UI/Images/Background/Widgets/main_theme.ogg" type="AudioStream" id=3]
This file doesn't exist. This change breaks the menu music.

2019-09-02 15:42 UTC, LinuxDonald commented
@Jummit are you still working on this?

2019-09-02 15:56 UTC, Jummit commented
> @Jummit are you still working on this?

I sadly can't right now, because I have RSI and don't want it to get worse.

2019-09-08 17:31 UTC, aaronfranke commented
Superseded by https://github.com/unknown-horizons/godot-port/pull/43

2019-09-08 17:31 UTC, closed without merging