Make HUD react to selected units
unknown-horizons/godot-port pull request #51
Opened 2020-03-12 11:33 UTC by Royber121

My naive try to implement changing of the HUD when a ship is selected.

2020-03-12 16:18 UTC, LinuxDonald commented
Thank you for the PR.
Are you done with it? Can it be reviewed or do you still work on it?

2020-03-12 16:44 UTC, aaronfranke requested changes

2020-03-12 16:44 UTC, aaronfranke commented on Assets/Player/PlayerHud.gd
> +
1. The style convention we are using for this project is to have 1 line between functions. Here you have 3.

2. Private functions (ones that start with an underscore that aren't *lifecycle* functions like _ready or _process) should go after public ones.

2020-03-12 18:23 UTC, Royber121 commented
Actually I'm still working on it. I will incorporate the requested changes.

2020-03-12 19:09 UTC, Royber121 commented
I just realized that artism was doing a lot of work on the GUI as well. I just had some free time and started to code, I hope I didnt't do something artism had in mind as well (and could do much better)

2020-03-14 14:31 UTC, Royber121 commented
I reverted develop and committed the changes to another branch HUD-updates-Unit-selection. I will close this PR and open another.

2020-03-14 14:31 UTC, closed without merging