Created a new ShipMenu-widget based on the old ShipTabMenuWidget.
unknown-horizons/godot-port pull request #52
Opened 2020-03-14 15:53 UTC by Royber121

Added a global EventBus.
Made the HUD appear, when a ship is selected.
-Ship is added to group "selected_units"
-Event "selected" is fired via EventBus
-PlayerHUD changes the visibility of the ShipMenu
-ShipMenu creates some inventory slots based on the ships num_of_slots

2020-03-16 14:04 UTC, Royber121 commented
Dammit, I hate git! I commited to the wrong branch. Ignore the last commit, when you merge the PR.

2020-03-16 19:33 UTC, aaronfranke requested changes
It doesn't seem to work properly:

![Screenshot from 2020-03-16 15-29-33](https://user-images.githubusercontent.com/1646875/76793362-4a28c880-679b-11ea-996a-ac2fb599ca93.png)

When it comes to Git, read through the [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) article in the Godot documentation, or if you prefer a graphical Git client, watch [my video on Git workflow using GitKraken](https://www.youtube.com/watch?v=0XKy8YpP5Ww).

2020-03-16 19:33 UTC, aaronfranke commented on Assets/UI/Scenes/TabWidget/ShipMenu.gd
> +	pass # Replace with function body.
Remove unused method.

2020-03-16 19:33 UTC, aaronfranke commented on Assets/UI/Scripts/TabWidget.gd
> +	pass
Remove unused `pass`, and consider removing (or commenting out) blocks which only contain `pass`.

2020-03-16 19:33 UTC, aaronfranke commented on Assets/UI/Scenes/TabWidget/ShipMenu.gd
> +	# first remove all slots from previous selection (if any)
Make comments start with a capital letter and end with a period.

2020-03-19 07:36 UTC, LinuxDonald commented
@Royber121 any update because of the requested changes?

2020-07-02 20:35 UTC, aaronfranke commented
Closing, PR author is inactive.

2020-07-02 20:35 UTC, closed without merging