Build dmg file only when running on Mac os
unknown-horizons/godot-port pull request #54
Opened 2020-04-02 10:12 UTC by baptistemesta

Since dmg file can only be built on Mac os, add a condition to do that only on ...Mac os :)

see https://github.com/unknown-horizons/godot-port/pull/53
https://en.wikipedia.org/wiki/Uname#Examples

2020-04-02 20:24 UTC, aaronfranke requested changes

2020-04-02 20:24 UTC, aaronfranke commented on build.sh
> +    echo "Exporting Mac os binary... "
Can you change this to "MacOS" or "macOS"? I prefer the former, though I mentioned the latter since it's Apple's official branding.

2020-04-03 06:33 UTC, baptistemesta commented on build.sh
> +    echo "Exporting Mac os binary... "
done

2020-04-03 06:35 UTC, aaronfranke approved these changes

2020-04-03 06:35 UTC, aaronfranke commented
Squashing-and-merging, thanks!

2020-04-03 06:35 UTC, baptistemesta commented
👍

2020-04-03 06:35 UTC, merged