Improved Camera Movement
unknown-horizons/godot-port pull request #58
Opened 2020-07-09 19:43 UTC by PetTurtle

Created CameraControls node with all camera movement logic
Added camera drag with middle mouse
Added camera zoom to mouse position
Refactored movement

2020-07-09 19:53 UTC, aaronfranke requested changes

2020-07-09 19:53 UTC, aaronfranke commented on Assets/Player/CameraControls.gd
> +onready var _rotation_y : Spatial = get_node(rotation_y_path)
When explicitly stating the type, do not include a space before the colon. (but do include a preceding space for `:=`)

2020-07-09 19:53 UTC, aaronfranke commented on Assets/Player/CameraControls.gd
> +			drag_dir /= _viewport_size / _camera.size
Division is an expensive operation and should be minimized. Do this instead:

    drag_dir *= _camera.size / _viewport_size

2020-07-09 19:53 UTC, aaronfranke commented on Assets/Player/CameraControls.gd
> +func _input(event):
While the GDScript style guide does state to use 2 lines between functions, Unknown Horizons uses 1 line.

2020-07-09 19:53 UTC, aaronfranke commented on Assets/Player/CameraControls.gd
> +	return enabled;
Unnecessary semicolon.

2020-07-11 08:30 UTC, aaronfranke requested changes

2020-07-11 08:30 UTC, aaronfranke commented on Assets/Player/CameraControls.tscn
> +[node name="CameraControls" type="Node"]
This should not be a scene.

2020-07-24 08:26 UTC, aaronfranke approved these changes
Style looks good. @artism90 Please review.

2020-07-26 18:46 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func _ready():
Add parameter types and return types to all functions. If there have been existing functions without them, it was most likely an oversight.

`func _ready() -> void:`

2020-07-26 18:47 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func _process(delta):
func _process(delta: float) -> void:

2020-07-26 18:47 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func _input(event):
`func _input(event: InputEvent) -> void:`

2020-07-26 18:48 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func _move(delta: float):
`func _move(delta: float) -> void:`

2020-07-26 18:48 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func _move_drag():
`func _move_drag() -> void:`

2020-07-26 18:48 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func _rotate(rotation: float):
`func _rotate(rotation: float) -> void:`

2020-07-26 18:48 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func _zoom(zoom_value: float):
`func _zoom(zoom_value: float) -> void:`

2020-07-26 18:49 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func set_enabled(new_value: bool):
`func set_enabled(new_value: bool) -> void:`

2020-07-26 18:49 UTC, artism90 commented on Assets/Player/CameraControls.gd
> +func _on_viewport_size_changed():
`func _on_viewport_size_changed() -> void:`

2020-07-26 19:09 UTC, pingwindev requested changes
Drag speed needs to be tweaked for higher resolutions. It's usable in a 1600x900 window but a bit slow on 1920p and way too slow on 4K. This can be addressed in a future PR though.

Please fix the mentioned code issues and rebase to the latest state.

2020-07-26 21:15 UTC, closed without merging