Wip interaction system
unknown-horizons/godot-port pull request #66
Opened 2020-08-29 13:01 UTC by Frogbeerr

The interaction System is in place. For detailed information look into Assets/Player/InteractionContext.gd. There I documented how to use it.

Currently the selection system is broken since I have yet to integrate it into the interaction system properly. I'll work on that next.

2020-08-30 00:23 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +"""This Node is a template for different behaiviors of the interaction system.
```suggestion
"""This Node is a template for different behaviors of the interaction system.
```

2020-08-30 00:23 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +E.g. a build menu could invoke a switch to it's own InteractionContext to handle
```suggestion
E.g. a build menu could invoke a switch to its own InteractionContext to handle
```

2020-08-30 00:23 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +the display of ghost buildings and later the placement of actual building.
```suggestion
the display of ghost buildings and later the placement of actual buildings.
```

2020-08-30 00:23 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +If a military unit is selected the system could swap to an InteractionContext
```suggestion
If a military unit is selected, the system could swap to an InteractionContext
```

2020-08-30 00:23 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +					 active InteractionContext to the one Provided as parameter.
```suggestion
					 active InteractionContext to the one provided as parameter.
```

2020-08-30 00:23 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +	abort_context - This signals causes the interaction system to revert to the
```suggestion
	abort_context - This signal causes the interaction system to revert to the
```

2020-08-30 00:23 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +Each of these actions will be routed to a method identified by it's name.
```suggestion
Each of these actions will be routed to a method identified by its name.
```

2020-08-30 00:23 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +The mehtod should be constructed as follows:
```suggestion
The method should be constructed as follows:
```

2020-08-30 00:29 UTC, artism90 commented on Assets/UI/Scripts/CityInfo.gd
> +export(int) var faction := 0 setget set_faction
This isn't necessary. `Global.Faction` is an enum.

2020-08-30 00:29 UTC, artism90 commented on Assets/World/Game.gd
> +func unhandled_input(event: InputEvent)->void:
```suggestion
func unhandled_input(event: InputEvent) -> void:
```

2020-08-30 00:33 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +var active_context : InteractionContext
```suggestion
var active_context: InteractionContext
```

2020-08-30 00:38 UTC, artism90 reviewed
I will check the code later in the editor, so just skimming it here for obvious and stylistic issues.

By the way, you can mark a PR as a "Draft PR" in the dropdown below. Please use this as long as it's WIP.

2020-09-13 00:30 UTC, LinuxDonald commented
@artism90 please final review and merge please

2020-09-13 17:15 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +"""This Node is a template for different behaiviors of the interaction system.
We don't use docstrings. The default comment style in GDScript is via `#`.

2020-09-13 17:19 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +
Only one line space before/after functions.
```suggestion

```

2020-09-13 17:19 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +func interact(event:InputEvent, target:Node, position:Vector3) -> void:
```suggestion
func interact(event: InputEvent, target: Node, position: Vector3) -> void:
```

2020-09-13 17:20 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +export (String) var _context_name = "Basic Interaction Context"
```suggestion
export(String) var _context_name = "Basic Interaction Context"
```

2020-09-13 17:20 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +export (PoolStringArray) var valid_actions = ["main_command"]
```suggestion
export(PoolStringArray) var valid_actions = ["main_command"]
```

2020-09-13 17:20 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +				var function : String = make_function_name(
```suggestion
				var function: String = make_function_name(
```

2020-09-13 17:21 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +func make_function_name(action:String, pressed:bool=true) -> String:
```suggestion
func make_function_name(action: String, pressed: bool = true) -> String:
```

2020-09-13 17:21 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +	var func_name : String = action.replace(" ", "_")
```suggestion
	var func_name: String = action.replace(" ", "_")
```

2020-09-13 17:22 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +func _on_mouse_motion(event:InputEventMouseMotion, target:Node, position:Vector3)->void:
```suggestion
func _on_mouse_motion(event: InputEventMouseMotion, target: Node, position: Vector3) -> void:
```

2020-09-13 17:23 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +export (int) var selection_tolerance = 10
```suggestion
export(int) var selection_tolerance = 10
```

2020-09-13 17:23 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +var sel_pos_start : Vector3
```suggestion
var sel_pos_start: Vector3
```

2020-09-13 17:24 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +var sel_pos_end : Vector3
```suggestion
var sel_pos_end: Vector3
```

2020-09-13 17:24 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +
```suggestion

```

2020-09-13 17:24 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +func _on_ia_alt_command_pressed(target : Node, position : Vector3) -> void:
```suggestion
func _on_ia_alt_command_pressed(target: Node, position: Vector3) -> void:
```

2020-09-13 17:25 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +	"""Start selection"""
```suggestion
	# Start selection
```

2020-09-13 17:25 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +func _on_ia_alt_command_released(target : Node, position : Vector3) -> void:
```suggestion
func _on_ia_alt_command_released(target: Node, position: Vector3) -> void:
```

2020-09-13 17:26 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +	"""End selection"""
```suggestion
	# End selection
```

2020-09-13 17:26 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +	var selection : Array
```suggestion
	var selection: Array
```

2020-09-13 17:26 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +	var top_left : Vector2 = get_viewport().get_camera().unproject_position(sel_pos_start)
```suggestion
	var top_left: Vector2 = get_viewport().get_camera().unproject_position(sel_pos_start)
```

2020-09-13 17:26 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +	var bot_right : Vector2 = get_viewport().get_camera().unproject_position(sel_pos_end)
```suggestion
	var bot_right: Vector2 = get_viewport().get_camera().unproject_position(sel_pos_end)
```

2020-09-13 17:27 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +func _on_ia_main_command_pressed(target : Node, position : Vector3) -> void:
```suggestion
func _on_ia_main_command_pressed(target: Node, position: Vector3) -> void:
```

2020-09-13 17:27 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +	"""Abort selection"""
```suggestion
	# Abort selection
```

2020-09-13 17:27 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +func get_selected_units(top_left : Vector2, bot_right : Vector2) -> Array:
```suggestion
func get_selected_units(top_left: Vector2, bot_right: Vector2) -> Array:
```

2020-09-13 17:28 UTC, artism90 commented on Assets/Player/InteractionContexts/SelectionContext.gd
> +	var selected_units : Array =  []
```suggestion
	var selected_units: Array = []
```

2020-09-13 17:31 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +func _ready():
```suggestion
func _ready() -> void:
```

2020-09-13 17:33 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +
```suggestion

```

2020-09-13 17:33 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +### INTERACTION SYSTEM ###
```suggestion
# Interaction system
```

2020-09-13 17:34 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +func switch_context(new_context : InteractionContext) -> void:
```suggestion
func switch_context(new_context: InteractionContext) -> void:
```

2020-09-13 17:34 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +
```suggestion

```

2020-09-13 17:35 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +	var target_object : Node
```suggestion
	var target_object: Node
```

2020-09-13 17:35 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +	var target_pos : Vector3
```suggestion
	var target_pos: Vector3
```

2020-09-13 17:35 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +
```suggestion

```

2020-09-13 17:35 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +func set_selection(new_sel : Array) -> void:
```suggestion
func set_selection(new_sel: Array) -> void:
```

2020-09-13 17:37 UTC, artism90 commented on Assets/Player/PlayerHud.gd
> +func _gui_input(event:InputEvent)->void:
```suggestion
func _gui_input(event: InputEvent) -> void:
```

2020-09-13 17:38 UTC, artism90 commented on Assets/UI/Scripts/SelectionBox.gd
> +export (Color) var line_color = Color(1, 1, 1)
```suggestion
export(Color) var line_color = Color(1, 1, 1)
```

2020-09-13 17:38 UTC, artism90 commented on Assets/UI/Scripts/SelectionBox.gd
> +export (int) var line_width = 1
```suggestion
export(int) var line_width = 1
```

2020-09-13 17:39 UTC, artism90 commented on Assets/UI/Scripts/SelectionBox.gd
> +		var top_left : Vector2 = get_viewport().get_camera().unproject_position(sel_pos_start)
```suggestion
		var top_left: Vector2 = get_viewport().get_camera().unproject_position(sel_pos_start)
```

2020-09-13 17:39 UTC, artism90 commented on Assets/UI/Scripts/SelectionBox.gd
> +func set_sel_pos_start(tl : Vector3) -> void:
```suggestion
func set_sel_pos_start(tl: Vector3) -> void:
```

2020-09-13 17:47 UTC, artism90 commented on Assets/UI/Scripts/ShipMenuTabWidget.gd
> +#	faction_indicator.texture = Global.FACTION_FLAGS[Global.faction]
Why is this out commented? When I revert it back within your PR, it works fine.
```suggestion
func _ready() -> void:
	faction_indicator.texture = Global.FACTION_FLAGS[Global.faction]
```

2020-09-13 18:02 UTC, artism90 requested changes
I went again through the code for style issues, since I've spot of lot of them while studying it, so above are all occurrences that need to be addressed so far and a few other remarks.

The code style generally follows the [official GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide).

Exceptions:
`extends`, then `class_name`.
Generally one line space instead of two where it says in the official guide.

2020-09-13 19:01 UTC, artism90 commented on Assets/Player/PlayerCamera.gd
> +	"""update selection"""
```suggestion
	# Update selection
```

2020-09-13 19:36 UTC, artism90 commented on Assets/UI/Scripts/SelectionBox.gd
> +onready var _p = get_parent()
Is this a leftover? It doesn't do anything right now.
```suggestion

```

2020-09-13 19:49 UTC, artism90 commented on Assets/Player/InteractionContext.gd
> +onready var _p := get_parent()
As a rule of thumb, better to follow an explicit, descriptive naming:
```suggestion
onready var _parent := get_parent()
```

2020-09-24 23:08 UTC, aaronfranke requested changes
For this to be approved, you will need to rebase, and then address the above feedback. If you need help rebasing, please see [this documentation article](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html), or watch [this video](https://www.youtube.com/watch?v=0XKy8YpP5Ww).

2020-10-27 18:20 UTC, merged

2020-10-27 19:03 UTC, artism90 commented
_Note: This was merged too early. I'll commit a few things directly later to fix remaining bugs._

Applied all suggestions/remaining changes since OP is inactive. Also squashed several pointless commits in between into the main one.
Side note: Existing player ship movement functionality is broken per this PR and has to be re-implemented within the interaction system as a `ShipMovementContext` or the like.