Add menu tab widget for foreign ships
unknown-horizons/godot-port pull request #94
Opened 2022-03-18 18:20 UTC by hepfnepf

I added a menu tab widget for non player ships: ~ShipAlienMenuTabWidget~`ShipForeignMenuTabWidget`. It displays the owner's correct flag and the ship name. The normal `ShipMenuTabWidget` now also displays the name of the ship.

2022-03-19 11:31 UTC, LinuxDonald commented
Thank you @artism90 will review it.

2022-03-19 12:31 UTC, artism90 requested changes
See review notes. Also rename the tab widget scene to `ShipForeignMenuTabWidget`.

Furthermore, always save files with `Trim Trailing Whitespace On Save` enabled:
![Screenshot 2022-03-19 132707](https://user-images.githubusercontent.com/2534873/159121166-ae0ada8c-be4e-42a2-898f-859b8974dc73.png)

2022-03-19 12:31 UTC, artism90 commented on Assets/Player/PlayerHUD.gd
> +	SHIP_ALIEN,
```suggestion
	SHIP_FOREIGN,
```
"Alien" sounds weird in this context. Let it be "Foreign".

2022-03-19 12:31 UTC, artism90 commented on Assets/Player/PlayerHUD.gd
>  			break
```suggestion
				new_context = UIContext.SHIP_ALIEN
			
			context_data = {
				"FactionIndicator": Global.FACTION_FLAGS[entity.faction],
				"Caption": entity.unit_name,
			}
			
			break
```
Formatting.

2022-03-19 12:31 UTC, artism90 commented on Assets/UI/Scripts/ShipAlienMenuTabWidget.gd
> +class_name ShipAlienMenuTabWidget
```suggestion
class_name ShipForeignMenuTabWidget
```

2022-03-19 12:31 UTC, artism90 commented on Assets/UI/Scripts/ShipAlienMenuTabWidget.gd
> +		if (data == "FactionIndicator"):
```suggestion
		if data == "FactionIndicator":
```
Redundant parentheses.

2022-03-20 13:19 UTC, artism90 requested changes
The node name of the embedded tab widget inside `PlayerHUD.tscn` still must be renamed.

**Note:** Do not add a new commit for this single fix, but amend it to the previous one. You can do it by `git commit --amend` or with any advanced git GUI application (e.g. GitKraken).

![image](https://user-images.githubusercontent.com/2534873/159164055-6bcfcacc-e714-491d-b75a-efa8c8ecd184.png)

2022-03-21 10:31 UTC, hepfnepf commented
Sorry for not amending. Read that part later.

2022-03-21 18:27 UTC, merged